### PR TITLE
updated package version to 2.1.0-cdo.0

### PR DESCRIPTION
**Pull request by fisher-alice**
This PR sets the johnny-five package version which has been updated to the latest release (v2.1.0) of mainline johnny-five from 0.11.1-cdo.2 to 2.1.0-cdo.0.

### CODE REVIEW

**Comment by bencodeorg** [comment]
For my understanding, do you happen to know where does the -cdo.2 suffix convention come from? Guessing the -cdo part signifies "this is a cdo fork of mainline version 2.1.0", but how about the .2?

**Comment by fisher-alice** [comment]
> 

Taking a look at the commit history of now [johnny-five-deprecated](https://github.com/code-dot-org/johnny-five-deprecated/commits/main), I see that Brad committed versions 0.11.1-cdo.0, 0.11.1-cdo.1, and 0.11.1-cdo.2 and seemed to  to update the cdo version with a feature change. 
Does that seem the case to you @bencodeorg ?

**Comment by bencodeorg** [comment]
Oh so you already pushed a new version to npm ([I see 2.1.0-cdo.2 here](https://www.npmjs.com/package/@code-dot-org/johnny-five))? Not sure if you checked in with others offline, but I feel like maybe it'd be better to go through this process (PR with version change in it) before pushing to NPM.

I wonder if we should have restarted with 2.1.0-cdo.0 (ie, this is basically a fresh fork with no cdo customizations at this point), but probably too late now.

**Review by bencodeorg — APPROVED** [review]

**Comment by fisher-alice** [comment]
> Oh so you already pushed a new version to npm ([I see 2.1.0-cdo.2 here](https://www.npmjs.com/package/@code-dot-org/johnny-five))? Not sure if you checked in with others offline, but I feel like maybe it'd be better to go through this process (PR with version change in it) before pushing to NPM.
> 
> I wonder if we should have restarted with 2.1.0-cdo.0 (ie, this is basically a fresh fork with no cdo customizations at this point), but probably too late now.

That's a great point, Ben! That does make sense. I was in the mode of testing the first Code.org customization in johnny-five and was trying to figure out why the source code uploaded on the build was not the latest release. I didn't realize that in order to push a new version on the registry, I needed to input a new release number. Sorry about that!

I can actually [unpublish this latest version](https://docs.npmjs.com/policies/unpublish#packages-published-less-than-72-hours-ago) within 72 hours from when it was published so I'll post on slack and get thoughts on how to go about version this updated johnny-five. Thanks so much!

**Comment by fisher-alice** [comment]
Based on this [article](https://gofore.com/en/best-practices-for-forking-a-git-repo/), version 2.1.0-cdo.0 would be following the convention described and also historically used. Thanks @bencodeorg ! I unpublished version 2.1.0-cdo.2 and plan to republish once this is merged.

**Comment by bencodeorg** [comment]
Sounds good to me, thanks for the research @fisher-alice !

**Pull request merged**
